######################################################################
# Automatically generated by qmake (2.01a) ? ??? 20 16:18:38 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MyMainWindow.h
SOURCES += main.cpp MyMainWindow.cpp
