######################################################################
# Automatically generated by qmake (2.01a) ? ??? 1 23:31:05 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += abstractproject.h qmakeproject.h
SOURCES += abstractproject.cpp main.cpp qmakeproject.cpp
